load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "wykobi",
    visibility = ["//visibility:public"],
    srcs = [
    "wykobi.hpp",
    "wykobi.inl",
    "wykobi_algorithm.hpp",
    "wykobi_axis_projection_descriptor.inl",
    "wykobi_build.cpp",
    "wykobi_clipping.inl",
    "wykobi_duplicates.inl",
    "wykobi_earclipping.inl",
    "wykobi_graphics_net.hpp",
    "wykobi_graphics_opengl.hpp",
    "wykobi_graphics_vcl.hpp",
    "wykobi_gui.hpp",
    "wykobi_hull.inl",
    "wykobi_instantiate.hpp",
    "wykobi_math.hpp",
    "wykobi_matrix.hpp",
    "wykobi_matrix.inl",
    "wykobi_minimum_bounding_ball.inl",
    "wykobi_naive_group_intersections.inl",
    "wykobi_nd.hpp",
    "wykobi_nd.inl",
    "wykobi_normalization.inl",
    "wykobi_ordered_polygon.inl",
    "wykobi_utilities.hpp"
    ],
    hdrs = [
    "wykobi.hpp"
    ]
)
